"""initial_schema

Revision ID: 601fe698a69e
Revises: 
Create Date: 2026-05-04 15:40:42.387378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '601fe698a69e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('google_trends', 'reddit', 'rss', 'forum', 'youtube', 'licensed_api', 'pharmacy_import', name='sourcetype'), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_scraping_allowed', sa.Boolean(), nullable=False, comment='Set true only after verifying robots.txt and ToS allow scraping'),
    sa.Column('robots_txt_checked', sa.Boolean(), nullable=False, comment='Flag to confirm robots.txt was reviewed before enabling scraping'),
    sa.Column('lawful_basis', sa.String(length=64), nullable=True, comment='GDPR lawful basis for collecting from this source (e.g. legitimate_interest)'),
    sa.Column('terms_of_service_url', sa.String(length=2048), nullable=True, comment='URL to the ToS document reviewed before enabling this source'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes on why this source is included or excluded'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_fr', sa.String(length=128), nullable=True),
    sa.Column('name_nl', sa.String(length=128), nullable=True),
    sa.Column('name_de', sa.String(length=128), nullable=True),
    sa.Column('is_otc', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('trend_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True, comment='Sub-national region, e.g. Wallonia, Flanders, Île-de-France'),
    sa.Column('city', sa.String(length=128), nullable=True, comment='City-level demand signal, e.g. Brussels, Paris, Liège'),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('relative_change', sa.Numeric(precision=8, scale=4), nullable=True, comment='% change vs previous equivalent period'),
    sa.Column('engagement_count_weighted', sa.Numeric(precision=10, scale=2), nullable=True, comment='Engagement-weighted signal score — high-engagement posts count more'),
    sa.Column('period', sa.Enum('days_7', 'days_30', 'days_90', name='trendperiod'), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'country', 'region', 'city', 'source_type', 'signal_date', 'period', name='uq_trend_signal')
    )
    op.create_index(op.f('ix_trend_signals_country'), 'trend_signals', ['country'], unique=False)
    op.create_index(op.f('ix_trend_signals_signal_date'), 'trend_signals', ['signal_date'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('country', postgresql.ARRAY(sa.String(length=2)), nullable=True),
    sa.Column('is_competitor', sa.Boolean(), nullable=False),
    sa.Column('brand_group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_group_id'], ['brand_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    op.create_table('competitor_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('clean_text', sa.Text(), nullable=True),
    sa.Column('author_id_hash', sa.String(length=64), nullable=True, comment='SHA-256 of original author ID — pseudonymised per GDPR'),
    sa.Column('engagement_count', sa.Integer(), nullable=True),
    sa.Column('query_used', sa.String(length=512), nullable=True, comment='The exact search query / keyword used to collect this mention — for traceability'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=True, comment='raw_text is wiped and is_deleted=true after this date per GDPR retention policy'),
    sa.Column('qdrant_point_id', sa.UUID(as_uuid=False), nullable=True, comment='Link to Qdrant vector point for semantic search'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentions_country'), 'mentions', ['country'], unique=False)
    op.create_index(op.f('ix_mentions_published_at'), 'mentions', ['published_at'], unique=False)
    op.create_index(op.f('ix_mentions_text_hash'), 'mentions', ['text_hash'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('pharmacist', 'lab_user', 'admin', name='userrole'), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('brand_group_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_group_id'], ['brand_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name='fk_user_pharmacy', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.Enum('adverse_event', 'shortage', 'misinformation', 'competitor_spike', 'brand_spike', 'prescription_promotion', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alertseverity'), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mention_classifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mention_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', name='sentiment'), nullable=True),
    sa.Column('topic', sa.Enum('price', 'efficacy', 'side_effect', 'availability', 'packaging', 'recommendation', 'general', name='topic'), nullable=True),
    sa.Column('intent', sa.Enum('complaint', 'question', 'purchase_intent', 'comparison', 'recommendation', 'other', name='intent'), nullable=True),
    sa.Column('risk_type', sa.Enum('adverse_event', 'misinformation', 'counterfeit', 'shortage', 'none', name='risktype'), nullable=False),
    sa.Column('is_adverse_event_candidate', sa.Boolean(), nullable=False),
    sa.Column('is_prescription_promotion', sa.Boolean(), nullable=False, comment='Flagged if mention promotes prescription medicine — pharma regulatory guard'),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('review_status', sa.Enum('pending', 'reviewed', 'escalated', 'dismissed', name='reviewstatus'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mention_id')
    )
    op.create_table('mention_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mention_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.Enum('brand', 'product', 'competitor', 'ingredient', 'category', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacies_country'), 'pharmacies', ['country'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active_ingredient', sa.String(length=255), nullable=True),
    sa.Column('cnk', sa.String(length=32), nullable=True),
    sa.Column('ean', sa.String(length=32), nullable=True),
    sa.Column('is_otc', sa.Boolean(), nullable=False),
    sa.Column('is_prescription', sa.Boolean(), nullable=False),
    sa.Column('country', postgresql.ARRAY(sa.String(length=2)), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_cnk'), 'products', ['cnk'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('search_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('countries', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=5)), nullable=False),
    sa.Column('time_window', sa.Enum('days_7', 'days_30', 'days_90', name='timewindow'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adverse_event_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mention_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Enum('pending', 'reviewed', 'escalated', 'dismissed', 'reported', name='adverseeventreviewstatus'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pharmacovigilance_ref', sa.String(length=128), nullable=True, comment='External pharmacovigilance system reference number after escalation'),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of email notification sent to pharmacovigilance team'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mention_id')
    )
    op.create_table('competitor_group_products',
    sa.Column('competitor_group_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_group_id'], ['competitor_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('competitor_group_id', 'product_id')
    )
    op.create_table('pharmacy_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pharmacy_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('alias_type', sa.Enum('brand', 'generic', 'misspelling', 'local_name', 'ingredient', 'category_term', name='aliastype'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_aliases_alias'), 'product_aliases', ['alias'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='Category-level recommendation when no specific product is identified'),
    sa.Column('recommendation_type', sa.Enum('stock_missing', 'reorder_trending', 'watch_category', 'deprioritise', name='recommendationtype'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('external_trend_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='Normalised 0–1 score from external demand signals (Google Trends, forums)'),
    sa.Column('internal_sales_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='Normalised 0–1 score from pharmacy own sales velocity'),
    sa.Column('inventory_gap_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='Normalised 0–1 score representing the stocking gap vs demand'),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='Composite: (external*0.5) + (inventory_gap*0.35) + (sales*0.15)'),
    sa.Column('action', sa.Enum('add', 'monitor', 'reorder', 'ignore', name='recommendationaction'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'dismissed', name='recommendationstatus'), nullable=False),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Evidence-linked source URLs supporting this recommendation per pharma compliance rules'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_topic_competitors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_topic_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_topic_id'], ['search_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_topic_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_topic_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['search_topic_id'], ['search_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_topic_sources')
    op.drop_table('search_topic_competitors')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_product_aliases_alias'), table_name='product_aliases')
    op.drop_table('product_aliases')
    op.drop_table('pharmacy_sales')
    op.drop_table('pharmacy_inventory')
    op.drop_table('competitor_group_products')
    op.drop_table('adverse_event_candidates')
    op.drop_table('search_topics')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_cnk'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_pharmacies_country'), table_name='pharmacies')
    op.drop_table('pharmacies')
    op.drop_table('mention_entities')
    op.drop_table('mention_classifications')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mentions_text_hash'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_published_at'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_country'), table_name='mentions')
    op.drop_table('mentions')
    op.drop_table('competitor_groups')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_trend_signals_signal_date'), table_name='trend_signals')
    op.drop_index(op.f('ix_trend_signals_country'), table_name='trend_signals')
    op.drop_table('trend_signals')
    op.drop_table('product_categories')
    op.drop_table('data_sources')
    op.drop_table('brand_groups')
    # ### end Alembic commands ###
